### ISSUE TITLE
Compiling qt5 for Fiji K3 routing error, libmysqlclient dependency has been compiled, please see what reason?

### ISSUE THREAD

**Issue by zxlhhyccc** [Lankaster/qt5-openwrt#1]
![~_ONY)9JBIBU$ZQ9P(V%Y~T](https://user-images.githubusercontent.com/45259624/63257204-d3325c80-c2ab-11e9-9634-733d4d95a9c4.png)

**Comment by Lankaster** [comment]
Can you check it again ?
