### ISSUE TITLE
Qt5-openwrt did not compile SSL, which affected qb search and connection. Can it be fixed? !

### ISSUE THREAD

**Issue by zxlhhyccc** [Lankaster/qt5-openwrt#3]

**Comment by zxlhhyccc** [comment]
In addition, one is that mysql is generally not required, so it is not recommended to compile. The other is whether the version can be updated to 5.13.1?

**Comment by Lankaster** [comment]
I need qt5-mysql
Regarding upgrade see https://github.com/Lankaster/qt5-openwrt/commit/13e6fa31da9f4b70b6b43378ef28857747eb5e58
