### ISSUE TITLE
Compile error!

### ISSUE THREAD

**Issue by zxlhhyccc** [Lankaster/qt5-openwrt#4]
![{X)0M(A_WI7DUAU9)NF~`EA](https://user-images.githubusercontent.com/45259624/66120497-93ca9000-e60d-11e9-88cc-6b9995788f55.png)

**Comment by Lankaster** [comment]
@zxlhhyccc unfortunately i doesn't see error (it was early)
Can you show your configuration and feeds.conf ?

**Comment by Lankaster** [comment]
no answer
